name: Publish Documentation
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Install DocFX
        run: dotnet tool install -g docfx
        
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
        
      - name: Restore dependencies
        run: |
          cd Bank
          dotnet restore
          
      - name: Build solution
        run: |
          cd Bank
          dotnet build --no-restore
          
      - name: Run tests with coverage
        run: |
          cd Bank
          dotnet test --collect:"XPlat Code Coverage" --no-build
          
      - name: Generate coverage report
        run: |
          cd Bank
          ReportGenerator "-reports:./*/*/*/coverage.cobertura.xml" "-targetdir:Cobertura" -reporttypes:MarkdownSummaryGithub
          
      - name: Generate documentation metadata
        run: |
          cd Bank
          docfx metadata docfx.json
          
      - name: Build documentation
        run: |
          cd Bank
          docfx build docfx.json
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Bank/_site'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4